version: '3.7'

services:

    frontend:
        container_name: solidity-react-client
        build:
            context: .
            dockerfile: client/Dockerfile
        volumes:
            - './client:/app'
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - "blockchain-server"
        command: npm start
    backend:
        container_name: solidity-node-server
        build:
            context: .
            dockerfile: server/Dockerfile
        volumes:
            - './server:/app'
        ports:
            - 8888:8080
        depends_on:
            - "blockchain-server"
        command: /app/node_modules/nodemon/bin/nodemon.js ./src/app.js -e js,hbs,css
    blockchain-server:
        container_name: solidity-blockchain-server
        build:
            context: .
            dockerfile: blockchain/Dockerfile
        volumes:
            - './blockchain:/app'
            - './client/src/contracts:/app/build'
        network_mode: "host"
        command: "truffle migrate --network advanced"