const config = {
    INIT_WEB3: "INIT_WEB3",
    GET_ACCOUNTS_CHAIN: "GET_ACCOUNTS_CHAIN",
    INIT_ITEM_MANAGER_CONTRACT: "INIT_ITEM_MANAGER_CONTRACT",
    INIT_ITEM_CONTRACT: "INIT_ITEM_CONTRACT",
    CREATE_ITEM: "CREATE_ITEM",
    FETCH_ITEM: "FETCH_ITEM",
    CHANGE_META_MASK_ACC: "CHANGE_META_MASK_ACC"
};

export default config;